-- 1. Create lessons table
CREATE TABLE IF NOT EXISTS lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create vocabularies table (type: 'vocab' or 'kanji')
CREATE TABLE IF NOT EXISTS vocabularies (
    id TEXT PRIMARY KEY, -- Using string ID (e.g., 'v1', 'k1') to match original mock IDs
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE NOT NULL,
    level TEXT,
    kana TEXT NOT NULL,
    kanji TEXT NOT NULL,
    sino_vietnamese TEXT,
    details TEXT,
    components JSONB DEFAULT '[]'::jsonb,
    definition TEXT NOT NULL,
    example_jp TEXT,
    example_vi TEXT,
    type TEXT NOT NULL CHECK (type IN ('vocab', 'kanji')),
    favorite BOOLEAN DEFAULT false NOT NULL,
    status TEXT DEFAULT 'forgot' NOT NULL CHECK (status IN ('learned', 'forgot')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create sentences table (type: 'sentence')
CREATE TABLE IF NOT EXISTS sentences (
    id TEXT PRIMARY KEY, -- Using string ID (e.g., 's1') to match original mock IDs
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE NOT NULL,
    level TEXT,
    kana TEXT NOT NULL,
    kanji TEXT NOT NULL,
    sino_vietnamese TEXT,
    details TEXT,
    components JSONB DEFAULT '[]'::jsonb,
    definition TEXT NOT NULL,
    example_jp TEXT NOT NULL,
    example_vi TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type = 'sentence'),
    favorite BOOLEAN DEFAULT false NOT NULL,
    status TEXT DEFAULT 'forgot' NOT NULL CHECK (status IN ('learned', 'forgot')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocabularies ENABLE ROW LEVEL SECURITY;
ALTER TABLE sentences ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies for public access (Single-user / Shared mode)
-- Policy for lessons (read only for safety, or all operations)
CREATE POLICY "Enable all access for lessons" ON lessons
    FOR ALL USING (true);

-- Policy for vocabularies (read and update/write for all)
CREATE POLICY "Enable all access for vocabularies" ON vocabularies
    FOR ALL USING (true);

-- Policy for sentences (read and update/write for all)
CREATE POLICY "Enable all access for sentences" ON sentences
    FOR ALL USING (true);

-- 6. Insert Seed Data
-- Clear existing records
TRUNCATE TABLE sentences CASCADE;
TRUNCATE TABLE vocabularies CASCADE;
TRUNCATE TABLE lessons CASCADE;

-- Insert Lessons (Note: IDs 1 and 2 will be generated)
INSERT INTO lessons (id, name, level) VALUES
(1, 'Lesson 1', 'N5'),
(2, 'Lesson 2', 'N5');

-- Reset identity sequences
ALTER TABLE lessons ALTER COLUMN id RESTART WITH 3;

-- Insert Vocabularies (types: 'vocab', 'kanji') for Lesson 1 and Lesson 2
INSERT INTO vocabularies (id, lesson_id, level, kana, kanji, sino_vietnamese, details, components, definition, example_jp, example_vi, type, favorite, status) VALUES
-- Lesson 1 vocabularies
('v1', 1, 'N5', 'べんきょうする', '勉強する', 'CỐ GẮNG & CƯỜNG TRÁNG', 'Âm Hán: MIỄN CƯỜNG', 
 '[{"char": "勉", "meaning": "Miễn (cố gắng hết sức)"}, {"char": "強", "meaning": "Cường (mạnh mẽ, cứng cáp)"}]'::jsonb,
 'Học tập, nghiên cứu', '毎日日本語を勉強しています。', 'Mỗi ngày tôi đều học tiếng Nhật.', 'vocab', false, 'forgot'),

('v2', 1, 'N5', 'たべる', '食べる', 'ĂN UỐNG / THỰC PHẨM', 'Âm Hán: THỰC', 
 '[{"char": "食", "meaning": "Thực (ăn / đồ ăn)"}]'::jsonb,
 'Ăn', 'レストランで晩ご飯を食べます。', 'Tôi ăn cơm tối ở nhà hàng.', 'vocab', true, 'forgot'),

('v3', 1, 'N4', 'よむ', '読む', 'ĐỌC SÁCH / PHÁT NGÔN', 'Âm Hán: ĐỘC', 
 '[{"char": "言", "meaning": "Bộ Ngôn (lời nói)"}, {"char": "売", "meaning": "Bộ Mại (bán buôn)"}]'::jsonb,
 'Đọc (sách, báo)', '図書館で小説を読みます。', 'Tôi đọc tiểu thuyết ở thư viện.', 'vocab', false, 'forgot'),

-- Lesson 1 kanji
('k1', 1, 'N5', 'べん', '勉', 'CỐ GẮNG / NỖ LỰC', 'Chữ Hán: MIỄN', 
 '[{"char": "力", "meaning": "Bộ Lực (sức mạnh)"}, {"char": "免", "meaning": "Chữ Miễn (tránh né)"}]'::jsonb,
 'Miễn (cố gắng)', '勉める (つとめる): Nỗ lực, cố gắng.', 'Chữ Miễn ghép trong Miễn Cường (Học tập).', 'kanji', false, 'forgot'),

-- Lesson 2 vocabularies
('v4', 2, 'N5', 'いく', '行く', 'DI CHUYỂN / HÀNH ĐỘNG', 'Âm Hán: HÀNH', 
 '[{"char": "彳", "meaning": "Bộ Xích (bước chân trái)"}, {"char": "亍", "meaning": "Bộ Súc (bước chân phải)"}]'::jsonb,
 'Đi', '明日東京へ行きます。', 'Ngày mai tôi sẽ đi Tokyo.', 'vocab', false, 'forgot'),

('v5', 2, 'N3', 'かんじょう', '感情', 'CẢM XÚC / CẢM TÍNH', 'Âm Hán: CẢM TÍNH', 
 '[{"char": "感", "meaning": "Cảm (cảm nhận, rung động)"}, {"char": "情", "meaning": "Tình (tình cảm, sự tình)"}]'::jsonb,
 'Cảm xúc, tình cảm', '彼女は感情が豊かな人です。', 'Cô ấy là một người dồi dào cảm xúc.', 'vocab', false, 'forgot'),

-- Lesson 2 kanji
('k2', 2, 'N4', 'こう', '行', 'DI CHUYỂN / HÀNH TRÌNH', 'Chữ Hán: HÀNH', 
 '[{"char": "彳", "meaning": "Bộ Xích"}, {"char": "亍", "meaning": "Bộ Súc"}]'::jsonb,
 'Hành (đi / hàng)', '行う (おこなう): Thực hiện, tiến hành.', 'Hành trình, ngân hàng, hành động.', 'kanji', true, 'forgot');

-- Insert Sentences for Lesson 1 and Lesson 2
INSERT INTO sentences (id, lesson_id, level, kana, kanji, sino_vietnamese, details, components, definition, example_jp, example_vi, type, favorite, status) VALUES
-- Lesson 1 sentences
('s1', 1, 'N5', 'これをたべます', 'これを食べます。', 'CẤU TRÚC TÂN NGỮ + ĐỘNG TỪ', 'Mẫu câu: Ăn cái này', 
 '[{"char": "これ", "meaning": "Cái này (chỉ thị từ)"}, {"char": "を", "meaning": "Trợ từ chỉ tân ngữ trực tiếp"}]'::jsonb,
 'Tôi ăn cái này.', 'りんごがあります.これを食べます。', 'Có quả táo. Tôi ăn cái này.', 'sentence', false, 'forgot'),

-- Lesson 2 sentences
('s2', 2, 'N4', 'いっしょにいきましょう', '一緒に行きましょう。', 'ĐỀ NGHỊ CÙNG LÀM VÀO HÀNH ĐỘNG', 'Mẫu câu: Cùng đi nhé', 
 '[{"char": "一緒に", "meaning": "Cùng nhau (trạng từ)"}, {"char": "ましょう", "meaning": "Đuôi rủ rê lịch sự"}]'::jsonb,
 'Chúng ta cùng đi nhé.', '天気がいいですね。一緒に行きましょう。', 'Thời tiết đẹp nhỉ. Chúng ta cùng đi nhé.', 'sentence', false, 'forgot');
