-- Create study_sessions table
CREATE TABLE IF NOT EXISTS study_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_cards INTEGER NOT NULL,
    learned_count INTEGER NOT NULL,
    forgot_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;

-- Create policy for public access (all operations allowed)
CREATE POLICY "Enable all access for study_sessions" ON study_sessions
    FOR ALL USING (true);
